- name: Remove older docker
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    update_cache: true

- name: Install required packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker CE repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Install required packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true

- name: Start Docker service
  service:
    name: docker
    state: "{{ docker_state | default('started') }}"
    enabled: yes
  tags: docker-service

- name: Copy Docker daemon config
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_config | to_nice_json }}"
  notify: restart docker
  tags: docker-config

- meta: flush_handlers
