---
box_name: "ubuntu/hirsute64"

providers:
  # VirtualBox
  virtualbox:
    enable: true

servers:
  - name: "kube-master01"
    cpu: 2
    ram: 4096
    ip: 192.168.56.11
    role: "master"

  - name: "kube-node01"
    cpu: 2
    ram: 2048
    ip: 192.168.56.21
    role: "node"
